### ISSUE TITLE
Pump: UART config section should be part of the corresponding component

### ISSUE THREAD

**Issue by danielschenk** [danielschenk/esphome-components#12]
Like this:
```yaml
switch:
  - platform: intex_sf90220rc1
    pump_id: pool_pump
    power_switch:
      id: pool_pump_power_switch
      name: Pool pump power

    uart:
      tx_pin: GPIO32
      rx_pin: GPIO33
      baud_rate: 2400
```
